name: test-fast-ctc-decoder

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: make setup-rust
      - name: Rust unit tests
        run: make rust-test
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Python unit tests
        run: |
          python3 -m pip install numpy .
          python3 tests/test_decode.py
